{"Functions": {"StaleObjectException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "", "history": "", "FullName": "StaleObjectException ()"}}, "Inheritance": ["https:##developer#android#com@B_java#lang#Object_E@", "https:##developer#android#com@B_java#lang#Throwable_E@", "https:##developer#android#com@B_java#lang#Exception_E@", "https:##developer#android#com@B_java#lang#RuntimeException_E@"], "ClassName": "android.support.test.uiautomator.StaleObjectException", "ClassDesc": "A @B_android#support#test#uiautomator#StaleObjectException_E@ exception is thrown when a @B_android#support#test#uiautomator#UiObject2_E@ is used after the underlying https:##developer#android#com@B_android#view#View_E@ has been destroyed. In this case, it is necessary to call @B_android#support#test#uiautomator#UiDevice#findObject_E@ to obtain a new @B_android#support#test#uiautomator#UiObject2_E@ instance."}