{"Functions": {"BindException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Construct a new BindException with no detailed message.", "history": "Added in API level 1", "FullName": "public BindException ()"}, "BindException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new BindException with the specified detail message as to why the bind error occurred. A detail message is a String that gives a specific description of this error.", "history": "Added in API level 1", "FullName": "public BindException (String msg)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#io#IOException_E@", "@B_java#net#SocketException_E@"], "ClassName": "java.net.BindException", "ClassDesc": "Signals that an error occurred while attempting to bind a socket to a local address and port. Typically, the port is in use, or the requested local address could not be assigned."}