{"Functions": {"CancellationException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CancellationException with no detail message.", "history": "Added in API level 1", "FullName": "public CancellationException ()"}, "CancellationException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CancellationException with the specified detail message.", "history": "Added in API level 1", "FullName": "public CancellationException (String message)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#lang#RuntimeException_E@", "@B_java#lang#IllegalStateException_E@"], "ClassName": "java.util.concurrent.CancellationException", "ClassDesc": "Exception indicating that the result of a value-producing task, such as a @B_java#util#concurrent#FutureTask_E@, cannot be retrieved because the task was cancelled."}