{"Functions": {"ExceptionInInitializerError(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: The exception thrown"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new ExceptionInInitializerError class by saving a reference to the Throwable object thrown for later retrieval by the @B_java#lang#ExceptionInInitializerError#getException_E@ method. The detail message string is set to null.", "history": "Added in API level 1", "FullName": "public ExceptionInInitializerError (Throwable thrown)"}, "ExceptionInInitializerError(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExceptionInInitializerError with the specified detail message string. A detail message is a String that describes this particular exception. The detail message string is saved for later retrieval by the @B_java#lang#Throwable#getMessage_E@ method. There is no saved throwable object.", "history": "Added in API level 1", "FullName": "public ExceptionInInitializerError (String s)"}, "getException()": {"Returns": [["@B_java#lang#Throwable_E@", "the saved throwable object of this ExceptionInInitializerError, or null if this ExceptionInInitializerError has no saved throwable object."]], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Returns the exception that occurred during a static initialization that caused this error to be created. This method predates the general-purpose exception chaining facility. The @B_java#lang#Throwable#getCause_E@ method is now the preferred means of obtaining this information.", "history": "Added in API level 1", "FullName": "public Throwable getException ()"}, "ExceptionInInitializerError()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExceptionInInitializerError with null as its detail message string and with no saved throwable object. A detail message is a String that describes this particular exception.", "history": "Added in API level 1", "FullName": "public ExceptionInInitializerError ()"}, "getCause()": {"Returns": [["@B_java#lang#Throwable_E@", "the cause of this error or null if the cause is nonexistent or unknown."]], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Returns the cause of this error (the exception that occurred during a static initialization that caused this error to be created).", "history": "Added in API level 1", "FullName": "public Throwable getCause ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Error_E@", "@B_java#lang#LinkageError_E@"], "ClassName": "java.lang.ExceptionInInitializerError", "ClassDesc": "Signals that an unexpected exception has occurred in a static initializer. An ExceptionInInitializerError is thrown to indicate that an exception occurred during evaluation of a static initializer or the initializer for a static variable. As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The \"saved throwable object\" that may be provided at construction time and accessed via the @B_java#lang#ExceptionInInitializerError#getException_E@ method is now known as the @B_java#lang#Throwable#getCause_E@ method, as well as the aforementioned \"legacy method.\""}