{"Functions": {"DateTimeException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the message to use for this exception, may be null"], ["@B_java#lang#Throwable_E@", "Throwable: the cause of the exception, may be null"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new date-time exception with the specified message and cause.", "history": "Added in API level 26", "FullName": "public DateTimeException (String message, Throwable cause)"}, "DateTimeException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the message to use for this exception, may be null"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new date-time exception with the specified message.", "history": "Added in API level 26", "FullName": "public DateTimeException (String message)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#lang#RuntimeException_E@"], "ClassName": "java.time.DateTimeException", "ClassDesc": "Exception used to indicate a problem while calculating a date-time. This exception is used to indicate problems with creating, querying and manipulating date-time objects."}