{"Functions": {"CertPathBuilderException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertPathBuilderException with the specified detail message and cause.", "history": "Added in API level 1", "FullName": "public CertPathBuilderException (String msg, Throwable cause)"}, "CertPathBuilderException(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertPathBuilderException that wraps the specified throwable. This allows any exception to be converted into a CertPathBuilderException, while retaining information about the wrapped exception, which may be useful for debugging. The detail message is set to (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).", "history": "Added in API level 1", "FullName": "public CertPathBuilderException (Throwable cause)"}, "CertPathBuilderException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertPathBuilderException with the given detail message. The detail message is a String that describes this particular exception in more detail.", "history": "Added in API level 1", "FullName": "public CertPathBuilderException (String msg)"}, "CertPathBuilderException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertPathBuilderException with null as its detail message.", "history": "Added in API level 1", "FullName": "public CertPathBuilderException ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#security#GeneralSecurityException_E@"], "ClassName": "java.security.cert.CertPathBuilderException", "ClassDesc": "An exception indicating one of a variety of problems encountered when building a certification path with a CertPathBuilder. A CertPathBuilderException provides support for wrapping exceptions. The @B_java#lang#Throwable#getCause_E@ method returns the throwable, if any, that caused this exception to be thrown. Unless otherwise specified, the methods defined in this class are not thread-safe. Multiple threads that need to access a single object concurrently should synchronize amongst themselves and provide the necessary locking. Multiple threads each manipulating separate objects need not synchronize."}