{"Functions": {"CompletionException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CompletionException with no detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 24", "FullName": "protected CompletionException ()"}, "CompletionException(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CompletionException with the specified cause. The detail message is set to (cause == null ? null : cause.toString()) (which typically contains the class and detail message of cause).", "history": "Added in API level 24", "FullName": "public CompletionException (Throwable cause)"}, "CompletionException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CompletionException with the specified detail message and cause.", "history": "Added in API level 24", "FullName": "public CompletionException (String message, Throwable cause)"}, "CompletionException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a CompletionException with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 24", "FullName": "protected CompletionException (String message)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#lang#RuntimeException_E@"], "ClassName": "java.util.concurrent.CompletionException", "ClassDesc": "Exception thrown when an error or other exception is encountered in the course of completing a result or task."}